const pizzaJson = [
    {
        id: 1,
        name: "Mussarela",
        img: "images/pizza.png",
        price: 25.00,
        sizes: ["100g", "530g", "860g"],
        description: `Deliciosa pizza de mussarela, com queijo derretido e saboroso. Perfeita para quem ama o sabor clássico da pizza.`,
    },
    {
        id: 2,
        name: "Calabresa",
        img: "images/pizza2.png",
        price: 22.00,
        sizes: ["320g", "530g", "860g"],
        description: `Pizza calabresa com linguiça calabresa artesanal, cebola roxa e pimentão verde. Uma explosão de sabores para os amantes de calabresa.`,
    },
    {
        id: 3,
        name: "Quatro Queijos",
        img: "images/pizza3.png",
        price: 24.00,
        sizes: ["320g", "530g", "860g"],
        description: `Combinação perfeita de quatro queijos: mussarela, provolone, gorgonzola e parmesão. Uma pizza cremosa e saborosa para todos os paladares.`,
    },
    {
        id: 4,
        name: "Americana",
        img: "images/pizza4.png",
        price: 26.00,
        sizes: ["320g", "530g", "860g"],
        description: `Pizza americana com molho de tomate, mussarela, pepperoni, hambúrguer e bacon. Uma pizza completa para os amantes de sabores intensos.`,
    },
    {
        id: 5,
        name: "Brigadeiro",
        img: "images/briga.png",
        price: 28.00,
        sizes: ["320g", "530g", "860g"],
        description: `Pizza de brigadeiro: doce tentação com massa crocante, brigadeiro cremoso e granulado. Para os apaixonados por chocolate.`,
    },
    {
        id: 6,
        name: "Moda da Casa",
        img: "images/pizza6.png",
        price: 25.00,
        sizes: ["320g", "530g", "860g"],
        description: `Pizza especial da casa com recheio variado, que muda a cada semana. Uma ótima opção para experimentar novos sabores.`,
    },
    {
        id: 7,
        name: "Chocolate",
        img: "images/pizza7.png",
        price: 29.00,
        sizes: ["320g", "530g", "860g"],
        description: `Pizza de chocolate com massa de brownie e recheio cremoso de chocolate. Uma sobremesa deliciosa para os amantes de chocolate.`,
    },
    {
        id: 8,
        name: "Calabresa com Champignon",
        img: "images/champignon.png",
        price: 27.00,
        sizes: ["100g", "530g", "860g"],
        description: `Deliciosa pizza de calabresa com champignon, coberta com queijo derretido e sabor inigualável. Perfeita para quem busca a combinação irresistível de sabores na clássica pizza.`,
    },
    {
        id: 9,
        name: "Baiana",
        img: "images/baiana.png",
        price: 24.00,
        sizes: ["100g", "530g", "860g"],
        description: `Pizza baiana: camarão, pimenta, cebola e coentro em uma explosão de sabores picantes, complementada pelo queijo derretido. Ideal para uma experiência ousada e cheia de personalidade.`,
    },
    {
        id: 10,
        name: "Vegetariana",
        img: "images/veg.png",
        price: 22.00,
        sizes: ["100g", "530g", "860g"],
        description: `Pizza vegetariana com vegetais frescos e queijo derretido, uma explosão de sabores leves e saudáveis em cada pedaço. Perfeita para os amantes de opções vegetarianas saborosas.`,
    },
    {
        id: 11,
        name: "Vegetariana 2",
        img: "images/veg2.png",
        price: 24.00,
        sizes: ["100g", "530g", "860g"],
        description: `Pizza vegetariana com abobrinha, berinjela, cogumelos e tomates, harmonizada com queijo derretido. Uma explosão de sabores frescos em cada pedaço.`,
    },
    {
        id: 12,
        name: "Bacon",
        img: "images/bacon.png",
        price: 27.00,
        sizes: ["100g", "530g", "860g"],
        description: `Pizza irresistível de bacon, com generosas camadas crocantes e sabor defumado. O queijo derretido completa essa experiência indulgente, tornando-a uma escolha perfeita para os amantes do bacon.`,
    }
];
